// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ack struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

type Version struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GameVariant          int32    `protobuf:"varint,2,opt,name=gameVariant,proto3" json:"gameVariant,omitempty"`
	GameStatus           int32    `protobuf:"varint,3,opt,name=gameStatus,proto3" json:"gameStatus,omitempty"`
	ListenAddr           string   `protobuf:"bytes,4,opt,name=listenAddr,proto3" json:"listenAddr,omitempty"`
	PeerList             []string `protobuf:"bytes,5,rep,name=peerList,proto3" json:"peerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetGameVariant() int32 {
	if m != nil {
		return m.GameVariant
	}
	return 0
}

func (m *Version) GetGameStatus() int32 {
	if m != nil {
		return m.GameStatus
	}
	return 0
}

func (m *Version) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *Version) GetPeerList() []string {
	if m != nil {
		return m.PeerList
	}
	return nil
}

type EncDeck struct {
	Deck                 [][]byte `protobuf:"bytes,1,rep,name=deck,proto3" json:"deck,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncDeck) Reset()         { *m = EncDeck{} }
func (m *EncDeck) String() string { return proto.CompactTextString(m) }
func (*EncDeck) ProtoMessage()    {}
func (*EncDeck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *EncDeck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncDeck.Unmarshal(m, b)
}
func (m *EncDeck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncDeck.Marshal(b, m, deterministic)
}
func (m *EncDeck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncDeck.Merge(m, src)
}
func (m *EncDeck) XXX_Size() int {
	return xxx_messageInfo_EncDeck.Size(m)
}
func (m *EncDeck) XXX_DiscardUnknown() {
	xxx_messageInfo_EncDeck.DiscardUnknown(m)
}

var xxx_messageInfo_EncDeck proto.InternalMessageInfo

func (m *EncDeck) GetDeck() [][]byte {
	if m != nil {
		return m.Deck
	}
	return nil
}

type TakeSeat struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TakeSeat) Reset()         { *m = TakeSeat{} }
func (m *TakeSeat) String() string { return proto.CompactTextString(m) }
func (*TakeSeat) ProtoMessage()    {}
func (*TakeSeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *TakeSeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeSeat.Unmarshal(m, b)
}
func (m *TakeSeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeSeat.Marshal(b, m, deterministic)
}
func (m *TakeSeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeSeat.Merge(m, src)
}
func (m *TakeSeat) XXX_Size() int {
	return xxx_messageInfo_TakeSeat.Size(m)
}
func (m *TakeSeat) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeSeat.DiscardUnknown(m)
}

var xxx_messageInfo_TakeSeat proto.InternalMessageInfo

func (m *TakeSeat) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*Ack)(nil), "Ack")
	proto.RegisterType((*Version)(nil), "Version")
	proto.RegisterType((*EncDeck)(nil), "EncDeck")
	proto.RegisterType((*TakeSeat)(nil), "TakeSeat")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x95, 0x2f, 0xfd, 0x93, 0xdc, 0x0f, 0x18, 0xcc, 0x62, 0x55, 0xa2, 0x4d, 0x33, 0x65,
	0x72, 0x24, 0x78, 0x82, 0x22, 0x10, 0x0c, 0x4c, 0x29, 0xea, 0xc0, 0xe6, 0x3a, 0x57, 0xa9, 0xe5,
	0xc6, 0x8e, 0x6c, 0xb7, 0xef, 0xc3, 0x9b, 0xa2, 0x38, 0x6d, 0x95, 0xc9, 0xbf, 0x73, 0xee, 0x91,
	0x8f, 0x7d, 0xe1, 0xb1, 0xb3, 0xc6, 0x9b, 0xd2, 0xa1, 0x3d, 0x4b, 0x81, 0x2c, 0xa8, 0x7c, 0x0a,
	0xf1, 0x46, 0xa8, 0xfc, 0x37, 0x82, 0xf9, 0x0e, 0xad, 0x93, 0x46, 0x13, 0x0a, 0xf3, 0xf3, 0x80,
	0x34, 0xca, 0xa2, 0x22, 0xad, 0xae, 0x92, 0x64, 0xf0, 0xbf, 0xe1, 0x2d, 0xee, 0xb8, 0x95, 0x5c,
	0x7b, 0xfa, 0x2f, 0x8b, 0x8a, 0x69, 0x35, 0xb6, 0xc8, 0x12, 0xa0, 0x97, 0x5b, 0xcf, 0xfd, 0xc9,
	0xd1, 0x38, 0x04, 0x46, 0x4e, 0x3f, 0x3f, 0x4a, 0xe7, 0x51, 0x6f, 0xea, 0xda, 0xd2, 0x49, 0xb8,
	0x7e, 0xe4, 0x90, 0x05, 0x24, 0x1d, 0xa2, 0xfd, 0x92, 0xce, 0xd3, 0x69, 0x16, 0x17, 0x69, 0x75,
	0xd3, 0xf9, 0x13, 0xcc, 0xdf, 0xb5, 0x78, 0x43, 0xa1, 0x08, 0x81, 0x49, 0x8d, 0x42, 0xd1, 0x28,
	0x8b, 0x8b, 0xbb, 0x2a, 0x70, 0xbe, 0x84, 0xe4, 0x9b, 0x2b, 0xdc, 0x22, 0xf7, 0xfd, 0x9c, 0xf7,
	0x05, 0xc3, 0xfb, 0x03, 0x3f, 0xb7, 0x30, 0xfb, 0x30, 0xce, 0xc9, 0x8e, 0xac, 0x20, 0xfd, 0xe4,
	0xba, 0x76, 0x07, 0xae, 0x90, 0x24, 0xec, 0xf2, 0xef, 0xc5, 0x8d, 0xc8, 0x0a, 0xee, 0xfb, 0xc0,
	0x11, 0xaf, 0x7d, 0x09, 0xbb, 0xd0, 0x62, 0xc2, 0x36, 0x42, 0x91, 0x35, 0x3c, 0x0c, 0x81, 0x5b,
	0x63, 0xca, 0xae, 0x38, 0x44, 0x5e, 0xd7, 0x3f, 0xab, 0x46, 0xfa, 0xc3, 0x69, 0xcf, 0x84, 0x69,
	0x4b, 0xae, 0xfd, 0xa1, 0x6e, 0xcb, 0xa6, 0xe9, 0x8c, 0x42, 0x5b, 0x86, 0xdd, 0xef, 0x67, 0xe1,
	0x78, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x76, 0xaf, 0xe0, 0x1a, 0x99, 0x01, 0x00, 0x00,
}
